
-- Inserta los datos
INSERT INTO EducationDegree (Name) VALUES
    ('Academy economist'),
    ('Administration'),
    ('Architect'),
    ('Assistant Data Programmer'),
    ('Associate of Arts'),
    ('B of Dental Hygiene'),
    ('B of Ed for the Comp School 1-7'),
    ('B of Ed for the Comp School 4-9'),
    ('B of Ed in Career Counselling'),
    ('B of Ed in Child and Youth Education'),
    ('B of Ed in Physical Education'),
    ('B of Sc in Behavioural Sciences'),
    ('B of Sc in Biomedical Laboratory Science'),
    ('B of Sc in Dietetics'),
    ('B of Sc in Engineering'),
    ('B of Sc in Fire Protection Engineering'),
    ('B of Sc in Nursing'),
    ('B of Sc in Occupational Therapy'),
    ('B of Sc in Pharmacy'),
    ('B of Sc in Physiotherapy'),
    ('B of Sc in Social Work'),
    ('B of Sc/M of Sc in Social Care'),
    ('B of/M of Theology'),
    ('B. ed'),
    ('B. eng'),
    ('B. law'),
    ('B. sc'),
    ('BA (specialised language for business)'),
    ('Bachelor'),
    ('Bachelor Finance'),
    ('Bachelor of business'),
    ('Bachelor of Business Administration'),
    ('Bachelor of laws'),
    ('Bachelor of Science (Economics and Business Administration)'),
    ('Bachelor, engineer'),
    ('Bachelor, humanities'),
    ('Bank clerk'),
    ('Basic commercial course'),
    ('BBA, Bachelor of Business Administration'),
    ('BSc (economics and business administration)'),
    ('BSc Engineering'),
    ('Building technician'),
    ('Business Administration, B.S.'),
    ('Cand agric'),
    ('Cand ed'),
    ('Cand jur'),
    ('Cand med'),
    ('Cand merc'),
    ('Cand musicae'),
    ('Cand odont'),
    ('Cand oecon'),
    ('Cand paed'),
    ('Cand pharm'),
    ('Cand philol'),
    ('Cand polit'),
    ('Cand psychol'),
    ('Cand real'),
    ('Cand san'),
    ('Cand scient'),
    ('Certification'),
    ('Chartered accountant'),
    ('Civil Architecht'),
    ('Civil Engineer'),
    ('Computer scientist'),
    ('Constructing architect'),
    ('Correspondent'),
    ('Datamatician (diploma in advanced computer studies)'),
    ('Design'),
    ('Dipl of Ed for the Folk High School'),
    ('Diploma'),
    ('Diploma in economics'),
    ('Doctorate'),
    ('Dr Art'),
    ('Dr Fil'),
    ('Dr Ing'),
    ('Dr Jur'),
    ('Dr Med'),
    ('Dr Oceon'),
    ('Dr Odont'),
    ('Dr Paed'),
    ('Dr Pharm'),
    ('Dr Philol'),
    ('Dr Philos'),
    ('Dr Polit'),
    ('Dr Psychol'),
    ('Dr Scient'),
    ('Dr Techn'),
    ('Dr Theol'),
    ('Education, M.Ed.'),
    ('Engineer'),
    ('Engineering'),
    ('Engineering courses'),
    ('Engineering diploma'),
    ('Estate agent'),
    ('Ex. Phil'),
    ('Examen Artium'),
    ('Examen oecon'),
    ('Financial economist'),
    ('Gen Degree of Computer Science'),
    ('Geography'),
    ('Grad Dipl in Midwifery'),
    ('Grad Dipl in Special Education'),
    ('High School'),
    ('Higher commercial examination'),
    ('Higher preparatory examination'),
    ('Higher technical examination'),
    ('Holder of a diploma in specialised business studies'),
    ('Holder of Diploma in Computer Science'),
    ('Insurance agent'),
    ('IT administrator'),
    ('IT degree'),
    ('Journalist'),
    ('Laboratory Technician'),
    ('Landscape architecht'),
    ('Librarian'),
    ('Lic.agr'),
    ('Lic.phil'),
    ('Lic.techn.'),
    ('Licentiate'),
    ('Lower secondary school leaving examiniation/10th grade/9th grade'),
    ('M of Ed for the Upper Secondary'),
    ('M of Sc in Psychology'),
    ('M of Sc in Veterinary Medicine'),
    ('M.A.'),
    ('M.Phil'),
    ('MA (communication)'),
    ('MA (political science)'),
    ('MA, Economics'),
    ('MA, Specialised language for business'),
    ('Mag.art'),
    ('Management course, other'),
    ('Market economist'),
    ('Master'),
    ('Master in agriculture'),
    ('Master in business'),
    ('Master in marketing'),
    ('Master of Administrative Sciences'),
    ('Master of Laws'),
    ('Master of Laws trained on bench'),
    ('Master of management'),
    ('Master of Science (Agriculture and Forestry)'),
    ('Master of Science (Economics and Business Administration)'),
    ('Master of Science (Technology)'),
    ('Master of Social Sciences'),
    ('MBA'),
    ('Microsoft certified programmer'),
    ('Microsoft certified systems developer'),
    ('MSc'),
    ('MSc (business administration and languages)'),
    ('MSc (economics and business administration)'),
    ('MSc (insurance science)'),
    ('MSc (mathematics and economics)'),
    ('MSc (public administration)'),
    ('MSc Information Technology'),
    ('MSc, Business administration and auditing'),
    ('MSc, Economy'),
    ('Music degree'),
    ('No title'),
    ('Occupational therapist'),
    ('Office, all round'),
    ('Other'),
    ('PhD'),
    ('Postgraduate Diploma'),
    ('Property administrator'),
    ('Psychoterapi'),
    ('Sales assistant'),
    ('Security'),
    ('Sociology degree'),
    ('Sports education'),
    ('State-authorised translator'),
    ('Teacher'),
    ('The banking diploma course'),
    ('The Danish Institute of Insurance Education, level 3-4'),
    ('The Danish Institute of Insurance Education, level 5-6'),
    ('Univ Dipl in Applied Technology'),
    ('Univ Dipl in Arts'),
    ('Univ Dipl in Dental Hygiene'),
    ('Univ Dipl in Marine Engineering'),
    ('Univ Dipl in Nautical Science'),
    ('University Degree in Dental Surgery'),
    ('Upper secondary school leaving examination'),
    ('Vocational Qualification in Business and Administration'),
    ('Vocational Qualification in Business Information Technology'),
    ('Other');
