INSERT INTO EducationSubject (Name) VALUES
    ('Acting'),
    ('Administration'),
    ('Administration/office'),
    ('Agriculture, forestry, fishing & animal welfare'),
    ('Archeology'),
    ('Architectural Technology'),
    ('Architecture'),
    ('Art & culture'),
    ('Astronomy'),
    ('Aviation'),
    ('Bank, finance & insurance'),
    ('Biology'),
    ('Building Conservation'),
    ('Building Technology'),
    ('Chemical'),
    ('Children and past times'),
    ('Clinical Psychology'),
    ('Construction'),
    ('Construction Management'),
    ('Counselling'),
    ('Culture'),
    ('Design'),
    ('Disability Nursing'),
    ('Economics'),
    ('Economics, accounting & auditing'),
    ('Education/children & youth'),
    ('Electronics'),
    ('Energy'),
    ('Engineer & technical work'),
    ('Engineering'),
    ('Engineering studies'),
    ('Environment'),
    ('Environmental and Sustainability Design & Studies'),
    ('Film & TV'),
    ('Fishing'),
    ('Food and drug'),
    ('Forestry'),
    ('Geology'),
    ('Health and Social Care'),
    ('Health Care'),
    ('Health Management'),
    ('History'),
    ('Hotel/Restaurant'),
    ('HR Management'),
    ('Human resources'),
    ('Industry'),
    ('Industry, trade & service'),
    ('Interior Architecture & Design'),
    ('IT and internet'),
    ('Journalism'),
    ('Landscape Architecture'),
    ('Languages'),
    ('Law'),
    ('Library'),
    ('Literature'),
    ('Maritime operations'),
    ('Marketing'),
    ('Materials preparation'),
    ('Mathematics'),
    ('Mechanical Engineering'),
    ('Media'),
    ('Media/Informasjon/Reklame/PR'),
    ('Medicine, health & care'),
    ('Medicine, health & care'),
    ('Mental Health Nursing'),
    ('Military'),
    ('Music'),
    ('Natural sciences'),
    ('Nursing'),
    ('Occupational Therapy'),
    ('Odontology'),
    ('Oecanography'),
    ('Organisation & management'),
    ('Other'),
    ('Pedagogic'),
    ('Pharmaceutical/biotech'),
    ('Pharmacy'),
    ('Philosophy'),
    ('Physical Therapy'),
    ('Physics'),
    ('Product Design'),
    ('Psychology'),
    ('Road and water'),
    ('Sales'),
    ('Security'),
    ('Security & emergency'),
    ('Shops/sale and purchase'),
    ('Social and humanistic sciences'),
    ('Social Anthropology'),
    ('Social sciences'),
    ('Social Work'),
    ('Sociology'),
    ('Speech and Language Therapy'),
    ('Sport'),
    ('Systematical Science'),
    ('Systems Technology'),
    ('Technical Assistance'),
    ('Telecom'),
    ('The humanities'),
    ('Theatre'),
    ('Theology'),
    ('Tourism'),
    ('Transport & logistics'),
    ('Transportation'),
    ('Urban Design and Planning'),
    ('Vehicle'),
    ('Veterinary science'),
    ('Zoology'),
    ('Other');